/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyhanghoa;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
/**
 *
 * @author Tung
 */
public class frmDangKy extends javax.swing.JFrame {

    /**
     * Creates new form frmDangKy
     */
    public frmDangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenNguoiDung = new javax.swing.JLabel();
        btnDangky = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtTenTK = new javax.swing.JTextField();
        txtTennguoidung = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMatkhau = new javax.swing.JPasswordField();
        txtNhaplaiMK = new javax.swing.JPasswordField();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblNhapLaiMK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTenNguoiDung.setText("Tên Người Dùng");

        btnDangky.setText("Đăng Ký");
        btnDangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkyActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtTennguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTennguoidungActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("ĐĂNG KÝ");

        lblTenTaiKhoan.setText("Tên tài khoản");

        lblMatKhau.setText("Mật khẩu");

        lblNhapLaiMK.setText("Nhập lại mật khẩu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenTK)
                                .addComponent(txtTennguoidung)
                                .addComponent(txtMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnDangky, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(106, 106, 106)
                                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTaiKhoan)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNhapLaiMK)
                    .addComponent(txtNhaplaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNguoiDung)
                    .addComponent(txtTennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangky, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkyActionPerformed
        // TODO add your handling code here:

        String tenDangNhap,matKhau,NhaplaiMatKhau,tenNguoiDung;
        tenDangNhap = txtTenTK.getText();
        matKhau = String.valueOf(txtMatkhau.getPassword()).trim();
        NhaplaiMatKhau = String.valueOf(txtNhaplaiMK.getPassword()).trim();
        tenNguoiDung = txtTennguoidung.getText().trim();
        //-----------------------------------------------------------
        String password,rePassword;
        password = txtMatkhau.getText().trim();
        rePassword = txtNhaplaiMK.getText().trim();
        if("".equals(tenDangNhap)){
            Main.thongBao("Tên đăng nhập không được bỏ trống","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if(KiemTra(tenDangNhap)){
            Main.thongBao("Tên đăng nhập đã tồn tại", "Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if(tenDangNhap.length() < 6){
            Main.thongBao("Tên đăng nhập phải từ 6 ký tự trở lên","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if(KiemTra(tenDangNhap)){
            Main.thongBao("Tên đăng nhập đã tồn tại", "Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if(!kiemTraChuVaSo(tenDangNhap)){
            Main.thongBao("Tên đăng nhập phải chứa chữ và số","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if("".equals(password)){
            Main.thongBao("Mật khẩu không được bỏ trống","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if("".equals(rePassword)){
            Main.thongBao("Nhập lại mật khẩu không được bỏ trống","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if(!rePassword.equals(password)){
            Main.thongBao("Nhập lại mật khẩu không đúng","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else if("".equals(tenNguoiDung)){
            Main.thongBao("Tên người dùng không được bỏ trống","Thông Báo", 1);
            txtTenTK.requestFocus();
        }
        else{
            String SQL = "insert into Users(Username,Password,Fullname)"
            + " values ('"+tenDangNhap+"','"+matKhau+"',N'"+tenNguoiDung+"')";
            Main.connection.ExcuteQueryUpdateDB(SQL);
            try{
                Thread.sleep(2000);
            }
            catch (InterruptedException ex) {
                System.out.println(ex.toString());
            }
            Main.thongBao("Đăng ký tài khoản thành công!!!","Thông Báo", 1);
            frmDangNhap frmdn = new frmDangNhap();
            frmdn.show();
            this.dispose();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex.toString());
            }
            Main.hienThiTaiKhoan = txtTenTK.getText();
            Main.hienThiMatKhauNguoiDung = txtMatkhau.getText();
            Main.hienThiTenNguoiDung = txtTennguoidung.getText();
        }
    }//GEN-LAST:event_btnDangkyActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
            "Bạn có muốn hủy đăng ký không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            frmDangNhap frmdn = new frmDangNhap();
            frmdn.show();
            this.dispose();
        }
        else{

        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtTennguoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTennguoidungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTennguoidungActionPerformed
    private boolean kiemTraChuVaSo(String chuoiCanKiemTra){
        boolean ketQua = false;
        Pattern p = Pattern.compile("[a-zA-Z][0-9]|[0-9][a-zA-Z]");
        Matcher m = p.matcher(chuoiCanKiemTra);
        ketQua = m.find();
        return ketQua;
    }
    private boolean KiemTra(String tenDangNhap){
        boolean ketQua = false;
        String SQL = "select * from Users where Username = '"+tenDangNhap+"'";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(SQL);
        try{
            if(rs.next()){
                ketQua = true;
            }
        }
        catch (Exception e) {
            System.out.println(e.toString());
        }
        return ketQua;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangky;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNhapLaiMK;
    private javax.swing.JLabel lblTenNguoiDung;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JPasswordField txtMatkhau;
    private javax.swing.JPasswordField txtNhaplaiMK;
    private javax.swing.JTextField txtTenTK;
    private javax.swing.JTextField txtTennguoidung;
    // End of variables declaration//GEN-END:variables
}
