/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyhanghoa;

import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Tung
 */
public class frmQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLY
     */
    public frmQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnQLSanPham = new javax.swing.JButton();
        btnQLyLoaiSP = new javax.swing.JButton();
        btnQLyPhanQuyen = new javax.swing.JButton();
        btnQLyNhanVien = new javax.swing.JButton();
        btnQLyKH = new javax.swing.JButton();
        lblHienThiQuyen = new javax.swing.JLabel();
        lblThongBao = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("TRANG CHỦ QUẢN LÝ");

        btnQLSanPham.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQLSanPham.setText("Quản lý Sản Phẩm");
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });

        btnQLyLoaiSP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQLyLoaiSP.setText("Quản lý Loại Sản Phẩm");
        btnQLyLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLyLoaiSPActionPerformed(evt);
            }
        });

        btnQLyPhanQuyen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQLyPhanQuyen.setText("Quản lý Phân Quyền");
        btnQLyPhanQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLyPhanQuyenActionPerformed(evt);
            }
        });

        btnQLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQLyNhanVien.setText("Quản lý Nhân Viên");
        btnQLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLyNhanVienActionPerformed(evt);
            }
        });

        btnQLyKH.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnQLyKH.setText("Quản lý Tài Khoản");
        btnQLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLyKHActionPerformed(evt);
            }
        });

        lblHienThiQuyen.setText("T ÀI KHOẢN ->");

        lblThongBao.setText("Thông Báo");

        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnQLyLoaiSP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLyPhanQuyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQLyKH)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHienThiQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLSanPham)
                    .addComponent(btnQLyLoaiSP))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQLyPhanQuyen)
                    .addComponent(btnQLyNhanVien))
                .addGap(34, 34, 34)
                .addComponent(btnQLyKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHienThiQuyen)
                    .addComponent(lblThongBao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangXuat)
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed
        // TODO add your handling code here:
        frmSanPham frmSP = new frmSanPham();
        frmSP.show();
    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void btnQLyLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLyLoaiSPActionPerformed
        // TODO add your handling code here:
        frmLoaiSanPham frmLSP = new frmLoaiSanPham();
        frmLSP.show();
    }//GEN-LAST:event_btnQLyLoaiSPActionPerformed

    private void btnQLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLyNhanVienActionPerformed
        // TODO add your handling code here:
        frmNhanVien frmNV = new frmNhanVien();
        frmNV.show();
    }//GEN-LAST:event_btnQLyNhanVienActionPerformed

    private void btnQLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLyKHActionPerformed
        // TODO add your handling code here:
        frmTaiKhoan frmnd = new frmTaiKhoan();
        frmnd.show();
    }//GEN-LAST:event_btnQLyKHActionPerformed

    private void btnQLyPhanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLyPhanQuyenActionPerformed
        // TODO add your handling code here:
        frmPhanQuyen frmQ = new frmPhanQuyen();
        frmQ.show();
    }//GEN-LAST:event_btnQLyPhanQuyenActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn thoát chương trình không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            System.exit(0);
        }
        else{
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //lblHienThiQuyen.setText("Đăng nhập bằng tài khoản:  " + Main.hienThiTenNguoiDung);
        if(frmDangNhap.Quyen == 1){
            lblThongBao.setText("Bạn đăng nhập bằng quyền ADMIN");
        }
        else if(frmDangNhap.Quyen == 2){
            lblThongBao.setText("Bạn đăng nhập bằng quyền IT");
            btnQLyKH.setEnabled(false);
            btnQLyPhanQuyen.setEnabled(false);
        }
        else if(frmDangNhap.Quyen == 3){
            lblThongBao.setText("Bạn vừa đăng nhập bằng quyền Nhân Viên");
            btnQLyNhanVien.setEnabled(false);
            btnQLyKH.setEnabled(false);
            btnQLyPhanQuyen.setEnabled(false);
            btnQLyLoaiSP.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn đăng xuất không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
            frmDangNhap frmdn = new frmDangNhap();
            frmdn.show();
            this.dispose();
        }
        else{}
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLSanPham;
    private javax.swing.JButton btnQLyKH;
    private javax.swing.JButton btnQLyLoaiSP;
    private javax.swing.JButton btnQLyNhanVien;
    private javax.swing.JButton btnQLyPhanQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblHienThiQuyen;
    private javax.swing.JLabel lblThongBao;
    // End of variables declaration//GEN-END:variables
}
